In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [ ]:
df = pd.read_csv("homeprices.csv")

In [ ]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [ ]:
model.predict([[3300]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([628715.75342466])

In [ ]:
model.coef_

array([135.78767123])

In [ ]:
model.intercept_

180616.43835616432

In [ ]:
model.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [ ]:
import pickle

In [ ]:
with open('model_pickle','wb') as f:
    pickle.dump(model,f)

In [ ]:
# from sklearn.externals import joblib
import joblib

In [ ]:
joblib.dump(model,'model_joblib')

['/content/drive/MyDrive/Colab Notebook Files/ML - YT Playlist by Codebasics/4) Save Model Using Joblib and Pickle/model_joblib']